FileVersion = 1
Projects = {Bulkan = {Path = "."}, VulkanTriangle = {Path = "VulkanTriangle"}, SDL2 = "*", "Bulkan.Utilities" = {Path = "Bulkan.Utilities"}}

[Workspace]
StartupProject = "VulkanTriangle"
