FileVersion = 1
Dependencies = {corlib = "*", Bulkan = "*"}

[Project]
Name = "Bulkan.Utilities"
TargetType = "BeefLib"
StartupObject = "Bulkan.Utilities.Program"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)/dist/Win32/Debug/VulkanMemoryAllocator.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)/dist/Win32/Release/VulkanMemoryAllocator.lib"]

[Configs.Paranoid.Win64]
LibPaths = ["$(ProjectDir)/dist/Win32/Release/VulkanMemoryAllocator.lib"]

[Configs.Test.Win64]
LibPaths = ["$(ProjectDir)/dist/Win32/Release/VulkanMemoryAllocator.lib"]
